# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('word', models.CharField(max_length=50)),
                ('url', models.TextField()),
                ('explainatin', models.TextField()),
                ('example', models.TextField()),
            ],
        ),
    ]
