# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 07:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 31, 7, 15, 29, 916846, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 31, 7, 15, 33, 973009, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
