# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 07:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='url',
            new_name='pronounce_url',
        ),
        migrations.AddField(
            model_name='word',
            name='pronounce',
            field=models.CharField(default=datetime.datetime(2016, 3, 31, 7, 38, 16, 479422, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
