# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 07:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0005_auto_20160412_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='next_review_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 28, 7, 5, 36, 730352, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
