# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0006_word_next_review_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='next_review_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
