# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0007_auto_20160428_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='graduated',
            field=models.BooleanField(default=False),
        ),
    ]
