# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0008_word_graduated'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='good',
            field=models.BooleanField(default=True),
        ),
    ]
